const pages=document.querySelectorAll('.app-page');
const navItems=document.querySelectorAll('.nav-item');
let newsCache=[];
const API='https://wnslzagpnsyzhutimpol.supabase.co/rest/v1/';
const KEY=window.acsadSupabaseKey||'sb_publishable_2VpkhXmf01sf0nzx3mC9zA_fzAcdOGB';
function showPage(name){pages.forEach(p=>p.classList.toggle('active',p.dataset.page===name));navItems.forEach(i=>i.classList.toggle('active',i.dataset.page===name));window.scrollTo({top:0,behavior:'smooth'});}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
async function get(table,query='select=*'){const r=await fetch(API+table+'?'+query,{headers:{apikey:KEY,Authorization:'Bearer '+KEY},cache:'no-store'});if(!r.ok)throw new Error(table+' '+r.status);return r.json();}
function renderNews(items){newsCache=items;const cards=items.map(x=>`<button class="news-card" data-article-id="${esc(x.id)}"><div class="news-img">${x.image_url?`<img src="${esc(x.image_url)}" alt="">`:'📰'}</div><div class="news-copy"><div class="meta">${esc(x.category||'ACSAD NEWS')}</div><h2>${esc(x.headline)}</h2><p>${esc((x.body||'').length>150?(x.body||'').slice(0,150)+'…':x.body||'')}</p><strong>READ MORE →</strong></div></button>`).join('');document.getElementById('home-news').innerHTML=cards.slice(0,3*cards.length).replace(/(<button)/g,'$1');document.getElementById('news-list').innerHTML=cards||'<div class="card"><p>No news published yet.</p></div>';if(items.length)document.getElementById('home-news').innerHTML=items.slice(0,3).map(x=>cardsFor(x)).join('');}
function cardsFor(x){return `<button class="news-card" data-article-id="${esc(x.id)}"><div class="news-img">${x.image_url?`<img src="${esc(x.image_url)}" alt="">`:'📰'}</div><div class="news-copy"><div class="meta">${esc(x.category||'ACSAD NEWS')}</div><h2>${esc(x.headline)}</h2><p>${esc((x.body||'').slice(0,150))}${(x.body||'').length>150?'…':''}</p><strong>READ MORE →</strong></div></button>`;}
function openArticle(id){const x=newsCache.find(a=>String(a.id)===String(id));if(!x)return;document.getElementById('article-detail').innerHTML=`<div class="article-image">${x.image_url?`<img src="${esc(x.image_url)}" alt="">`:'📰'}</div><div class="meta">${esc(x.category||'ACSAD NEWS')}${x.published_at?' • '+esc(new Date(x.published_at).toLocaleDateString('en-AU')):''}</div><h1>${esc(x.headline)}</h1><p class="article-body">${esc(x.body||'')}</p>`;showPage('article');}
function renderFixtures(items){document.getElementById('fixtures-list').innerHTML=items.length?items.map(x=>`<div class="card"><h2>${esc(x.home_team||'Alkimos College')} vs ${esc(x.away_team||x.opponent||'Opponent')}</h2><p><b>Date:</b> ${esc(x.date_label||x.fixture_date||'TBC')}</p><p><b>Sport:</b> ${esc(x.sport||'')}</p>${x.details?`<p>${esc(x.details)}</p>`:''}<span class="status">${esc(x.status||'CONFIRMED')}</span>${x.coverage_url?` <a class="text-btn link-btn" target="_blank" rel="noopener" href="${esc(x.coverage_url)}">COVERAGE ↗</a>`:''}</div>`).join(''):'<div class="card"><p>No fixtures published yet.</p></div>';}
function renderResults(items){document.getElementById('results-list').innerHTML=items.length?items.map(x=>`<div class="card"><div class="meta">${esc(x.event||'RESULT')} • ${esc(x.sport||'')}</div><h2>${esc(x.home_team)} ${x.home_score!=null?esc(x.home_score):'—'} — ${x.away_score!=null?esc(x.away_score):'—'} ${esc(x.away_team)}</h2><p>${esc(x.date_label||x.result_date||'')}${x.details?' • '+esc(x.details):''}</p></div>`).join(''):'<div class="card"><p>No results published yet.</p></div>';}
function renderRecords(items){document.getElementById('records-list').innerHTML=items.length?`<div class="table-wrap"><table><thead><tr><th>Event</th><th>Division</th><th>Record</th><th>Year</th><th>Holder</th></tr></thead><tbody>${items.map(x=>`<tr><td>${esc(x.event)}</td><td>${esc(x.division||'')}</td><td>${esc(x.record_value||'')}</td><td>${esc(x.year||'')}</td><td>${esc(x.holder||'')}</td></tr>`).join('')}</tbody></table></div>`:'<div class="card"><p>No records published yet.</p></div>';}
function renderReplays(items){document.getElementById('replays-list').innerHTML=items.length?items.map(x=>`<div class="card"><h2>🎥 ${esc(x.title)}</h2><p><b>Sport:</b> ${esc(x.sport||'')}<br><b>Date:</b> ${esc(x.date_label||x.replay_date||'')}</p>${x.description?`<p>${esc(x.description)}</p>`:''}<a class="primary-btn link-btn" target="_blank" rel="noopener" href="${esc(x.url)}">WATCH REPLAY ↗</a></div>`).join(''):'<div class="card"><p>No replays published yet.</p></div>';}
document.addEventListener('click',e=>{const p=e.target.closest('[data-page]');if(p){showPage(p.dataset.page);return;}const a=e.target.closest('[data-article-id]');if(a)openArticle(a.dataset.articleId);});
async function sync(){try{const [news,fixtures,results,records,replays]=await Promise.all([get('articles','select=id,headline,category,body,image_url,published_at&order=published_at.desc&limit=20'),get('fixtures','select=*&order=fixture_date.asc.nullslast'),get('results','select=*&order=result_date.desc.nullslast'),get('records','select=*&order=created_at.desc'),get('replays','select=*&order=replay_date.desc.nullslast')]);renderNews(news);renderFixtures(fixtures);renderResults(results);renderRecords(records);renderReplays(replays);}catch(e){console.warn('ACSAD sync unavailable:',e.message);}}
sync();