const pages=document.querySelectorAll('.app-page');
const navItems=document.querySelectorAll('.nav-item');
const fallbackNews=[
 {id:'fallback-1',headline:'Socrates crowned 2026 champions',category:'FACTION CARNIVAL • 4 SEPTEMBER 2026',body:"Green has won Alkimos College's 2026 high-school faction carnival by around 300 points.",image_url:'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=1000&q=80'},
 {id:'fallback-2',headline:'Aristotle athlete wins Champion Boy',category:'INDIVIDUAL',body:'A Year 7 Aristotle athlete collected a ribbon in every event.',image_url:'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=1000&q=80'},
 {id:'fallback-3',headline:'Plato take team-games trophy',category:'TEAM GAMES',body:'Plato claimed the minor team-games trophy during the 2026 carnival.',image_url:'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=1000&q=80'}
];
let newsCache=[...fallbackNews];
function showPage(name){pages.forEach(p=>p.classList.toggle('active',p.dataset.page===name));navItems.forEach(i=>i.classList.toggle('active',i.dataset.page===name));window.scrollTo({top:0,behavior:'smooth'});}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function newsCard(item){return `<button class="news-card" data-article-id="${escapeHtml(item.id)}"><div class="news-img">${item.image_url?`<img src="${escapeHtml(item.image_url)}" alt="">`:'📰'}</div><div class="news-copy"><div class="meta">${escapeHtml(item.category||'ACSAD NEWS')}</div><h2>${escapeHtml(item.headline)}</h2><p>${escapeHtml((item.body||'').length>150?(item.body||'').slice(0,150)+'…':item.body||'')}</p><strong>READ MORE →</strong></div></button>`;}
function renderNews(items){newsCache=items;document.getElementById('news-list').innerHTML=items.map(newsCard).join('');document.getElementById('home-news').innerHTML=items.slice(0,3).map(newsCard).join('');}
function openArticle(id){const item=newsCache.find(x=>String(x.id)===String(id));if(!item)return;document.getElementById('article-detail').innerHTML=`<div class="article-image">${item.image_url?`<img src="${escapeHtml(item.image_url)}" alt="">`:'📰'}</div><div class="meta">${escapeHtml(item.category||'ACSAD NEWS')}${item.published_at?' • '+escapeHtml(new Date(item.published_at).toLocaleDateString('en-AU')):''}</div><h1>${escapeHtml(item.headline)}</h1><p class="article-body">${escapeHtml(item.body||'')}</p>`;showPage('article');}
document.addEventListener('click',e=>{const page=e.target.closest('[data-page]');if(page){showPage(page.dataset.page);return;}const article=e.target.closest('[data-article-id]');if(article)openArticle(article.dataset.articleId);});
async function loadNews(){renderNews(fallbackNews);if(!window.acsadSupabase)return;try{const {data,error}=await window.acsadSupabase.from('articles').select('id,headline,category,body,image_url,published_at').order('published_at',{ascending:false}).limit(20);if(error)throw error;if(data&&data.length)renderNews(data);}catch(error){console.warn('ACSAD news sync unavailable:',error.message);}}
loadNews();